name: CI workflow

on:
  push:
    branches: push on main branch
  pull_request:
    branches: pull_request on main branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: python:3.9-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
